name: Publish on GitHub, CurseForge & Modrinth

env:
  MINECRAFT_VERSION: 1.19.2
  JAVA_VERSION: 17

permissions:
  contents: write

on:
  push:
    branches:
      main
    tags:
      v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Determine version
        run: |
          echo "MOD_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
          echo "MOD_VERSION = $MOD_VERSION"
